import { contextBridge, ipcRenderer } from 'electron';

const IPC = {
  getVersion: 'tellann:version',
  getSession: 'tellann:auth:session',
  signIn: 'tellann:auth:sign-in',
  signOut: 'tellann:auth:sign-out',
  getApplications: 'tellann:cloud:applications',
  listRuns: 'tellann:cloud:runs:list',
  getRun: 'tellann:cloud:runs:get',
  getRunReport: 'tellann:cloud:runs:report',
  getDeclaredFlows: 'tellann:cloud:intent:list',
  getDeclaredFlow: 'tellann:cloud:intent:get',
  createDeclaredFlow: 'tellann:cloud:intent:create',
  addDeclaredState: 'tellann:cloud:intent:state:add',
  addDeclaredTransition: 'tellann:cloud:intent:transition:add',
  completeDeclaredFlow: 'tellann:cloud:intent:complete',
  reopenDeclaredFlow: 'tellann:cloud:intent:reopen',
  importDocuments: 'tellann:documents:import',
  listDocuments: 'tellann:documents:list',
  getDocumentJob: 'tellann:documents:job:get',
  createIntentDraft: 'tellann:intent:draft:create',
  getIntentDraftJob: 'tellann:intent:draft:job:get',
  listIntentDrafts: 'tellann:intent:draft:list',
  getIntentDraft: 'tellann:intent:draft:get',
  reviewIntentDraft: 'tellann:intent:draft:review',
  correctIntentDraft: 'tellann:intent:draft:correct',
  openExternal: 'tellann:system:open-external',
  openProfile: 'tellann:system:open-profile',
  chooseWorkspace: 'tellann:workspace:choose',
  getLocalWorkspace: 'tellann:workspace:local-state',
  scanWorkspace: 'tellann:workspace:scan',
  startGuidedRun: 'tellann:run:start',
  pauseGuidedRun: 'tellann:run:pause',
  endGuidedRun: 'tellann:run:end',
  getRunState: 'tellann:run:state',
  detectInstrumentation: 'tellann:instrumentation:detect',
  proposeInstrumentation: 'tellann:instrumentation:propose',
  listInstrumentationPlans: 'tellann:instrumentation:plans:list',
  getInstrumentationPlan: 'tellann:instrumentation:plans:get',
  approveInstrumentation: 'tellann:instrumentation:approve',
  rejectInstrumentation: 'tellann:instrumentation:reject',
  applyInstrumentation: 'tellann:instrumentation:apply',
  validateInstrumentation: 'tellann:instrumentation:validate',
  rollbackInstrumentation: 'tellann:instrumentation:rollback',
  getLocalInstrumentationResult: 'tellann:instrumentation:local-result',
} as const;

contextBridge.exposeInMainWorld('tellann', {
  auth: {
    getSession: () => ipcRenderer.invoke(IPC.getSession),
    signIn: () => ipcRenderer.invoke(IPC.signIn),
    signOut: () => ipcRenderer.invoke(IPC.signOut),
  },
  projects: {
    list: () => ipcRenderer.invoke(IPC.getApplications),
    getLocalWorkspace: (applicationId: string) => ipcRenderer.invoke(IPC.getLocalWorkspace, applicationId),
    chooseWorkspace: () => ipcRenderer.invoke(IPC.chooseWorkspace),
    scanWorkspace: (input: { path: string; workspaceId: string; applicationId: string }) =>
      ipcRenderer.invoke(IPC.scanWorkspace, input),
  },
  intent: {
    listDeclaredFlows: (applicationId: string) => ipcRenderer.invoke(IPC.getDeclaredFlows, applicationId),
    getDeclaredFlow: (applicationId: string, flowId: string) => ipcRenderer.invoke(IPC.getDeclaredFlow, { applicationId, flowId }),
    createDeclaredFlow: (applicationId: string, name: string, workflowType: string) => ipcRenderer.invoke(IPC.createDeclaredFlow, { applicationId, name, workflowType }),
    addDeclaredState: (applicationId: string, flowId: string, stateName: string, category: string) => ipcRenderer.invoke(IPC.addDeclaredState, { applicationId, flowId, stateName, category }),
    addDeclaredTransition: (applicationId: string, flowId: string, fromStateId: string, toStateId: string, action?: string) => ipcRenderer.invoke(IPC.addDeclaredTransition, { applicationId, flowId, fromStateId, toStateId, action }),
    completeDeclaredFlow: (applicationId: string, flowId: string) => ipcRenderer.invoke(IPC.completeDeclaredFlow, { applicationId, flowId }),
    reopenDeclaredFlow: (applicationId: string, flowId: string) => ipcRenderer.invoke(IPC.reopenDeclaredFlow, { applicationId, flowId }),
    listDrafts: (applicationId: string) => ipcRenderer.invoke(IPC.listIntentDrafts, applicationId),
    getDraft: (applicationId: string, draftId: string) => ipcRenderer.invoke(IPC.getIntentDraft, { applicationId, draftId }),
    createDraft: (applicationId: string, documentVersionIds: string[]) => ipcRenderer.invoke(IPC.createIntentDraft, { applicationId, documentVersionIds }),
    getDraftJob: (applicationId: string, jobId: string) => ipcRenderer.invoke(IPC.getIntentDraftJob, { applicationId, jobId }),
    reviewDraft: (applicationId: string, draftId: string, review: unknown) => ipcRenderer.invoke(IPC.reviewIntentDraft, { applicationId, draftId, review }),
    correctDraft: (applicationId: string, draftId: string, correction: string) => ipcRenderer.invoke(IPC.correctIntentDraft, { applicationId, draftId, correction }),
  },
  documents: {
    list: (applicationId: string) => ipcRenderer.invoke(IPC.listDocuments, applicationId),
    import: (applicationId: string) => ipcRenderer.invoke(IPC.importDocuments, applicationId),
    getJob: (applicationId: string, jobId: string) => ipcRenderer.invoke(IPC.getDocumentJob, { applicationId, jobId }),
  },
  runs: {
    list: (applicationId: string) => ipcRenderer.invoke(IPC.listRuns, applicationId),
    get: (runId: string) => ipcRenderer.invoke(IPC.getRun, runId),
    getReport: (runId: string) => ipcRenderer.invoke(IPC.getRunReport, runId),
    start: (input: unknown) => ipcRenderer.invoke(IPC.startGuidedRun, input),
    pause: () => ipcRenderer.invoke(IPC.pauseGuidedRun),
    end: () => ipcRenderer.invoke(IPC.endGuidedRun),
    getActive: () => ipcRenderer.invoke(IPC.getRunState),
  },
  instrumentation: {
    detect: (input: unknown) => ipcRenderer.invoke(IPC.detectInstrumentation, input),
    propose: (input: unknown) => ipcRenderer.invoke(IPC.proposeInstrumentation, input),
    list: (applicationId: string) => ipcRenderer.invoke(IPC.listInstrumentationPlans, applicationId),
    get: (applicationId: string, planId: string) => ipcRenderer.invoke(IPC.getInstrumentationPlan, { applicationId, planId }),
    getLocalResult: (applicationId: string, planId: string) => ipcRenderer.invoke(IPC.getLocalInstrumentationResult, { applicationId, planId }),
    approve: (input: unknown) => ipcRenderer.invoke(IPC.approveInstrumentation, input),
    reject: (applicationId: string, planId: string, reason?: string) => ipcRenderer.invoke(IPC.rejectInstrumentation, { applicationId, planId, reason }),
    apply: (applicationId: string, planId: string) => ipcRenderer.invoke(IPC.applyInstrumentation, { applicationId, planId }),
    validate: (applicationId: string, planId: string) => ipcRenderer.invoke(IPC.validateInstrumentation, { applicationId, planId }),
    rollback: (applicationId: string, planId: string) => ipcRenderer.invoke(IPC.rollbackInstrumentation, { applicationId, planId }),
  },
  system: {
    getVersion: () => ipcRenderer.invoke(IPC.getVersion),
    openExternal: (url: string) => ipcRenderer.invoke(IPC.openExternal, url),
    openProfile: () => ipcRenderer.invoke(IPC.openProfile),
  },
});
