ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENVIRONMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENVIRONMENT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENVIRONMENT_DELETED';
