import type { Metadata } from "next";
import Link from "next/link";
import { DriftComparison, DriftMedia, DriftRoles } from "./media";
import "./page.css";
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://domain-name.com";
const appUrl = `${(process.env.NEXT_PUBLIC_APP_URL || "https://app.domain-name.com").replace(/\/$/, "")}/auth/login?plan=free`;
const title = "Graph Drift — Track Changes in Application Behavior | Tellann";
const description = "Compare behavioral graph versions with Tellann. See added and removed states, changed transitions, and coverage movement across application demonstrations.";
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: "/product/graph-drift" }, openGraph: { title, description, url: `${siteUrl}/product/graph-drift`, type: "website" } };
const faqs = [
    ["What is Graph Drift?", "Graph Drift compares versions of your application's behavioral graph to show added or removed states and transitions, changed transition frequencies, and coverage movement."],
    ["Does removed behavior mean something is broken?", "Not necessarily. A path may not have been exercised in the newer demonstration. Review the evidence and demonstrate it again to distinguish a coverage gap from behavior that became unreachable."],
    ["How is this different from Behavior Graphs?", "Behavior Graphs explain what the application did. Graph Drift compares versions to explain how that demonstrated behavior changed over time."],
    ["Does higher coverage mean higher quality?", "Higher coverage means more behavior was exercised. It is not a quality score or proof that the application is defect-free."],
    ["Does Graph Drift monitor production today?", "The Phase 1 scope compares demonstration evidence. Production-baseline drift is planned for Phase 2, and anomaly detection for Phase 3."],
    ["Can I compare behavior against declared intent?", "Yes. Graph Drift records observed-versus-declared drift over time. Reconciliation explains which intended behaviors were confirmed, remain absent, or were not declared."],
];
export default function GraphDriftPage() {
    const schema = { "@context": "https://schema.org", "@graph": [
            { "@type": "WebPage", name: title, description, url: `${siteUrl}/product/graph-drift` },
            { "@type": "BreadcrumbList", itemListElement: [["Home", ""], ["Product", "/product"], ["Graph Drift", "/product/graph-drift"]].map(([name, path], i) => ({ "@type": "ListItem", position: i + 1, name, item: `${siteUrl}${path}` })) },
            { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
        ] };
    return <main className="drift-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }}/>
    <section className="drift-hero drift-shell">
      <div className="drift-hero-copy" data-aos="fade-up"><p className="drift-kicker">Graph Drift / Behavioral change visibility</p><h1>See what changed in your application’s <em>behavior.</em></h1><p>Compare demonstrations. See which paths appeared, disappeared, or changed — and where coverage moved.</p><div className="drift-actions"><a className="drift-primary" href={appUrl}>Start a free trial <span>↗</span></a><a href="#how-it-works">See how it works <span>↓</span></a></div><small>Phase 1 · Based on demonstration evidence</small></div>
      <div className="drift-hero-art" data-aos="fade-up" data-aos-delay="120"><div className="drift-version"><span>BEFORE / v6</span><span>→</span><span>AFTER / v7</span></div><DriftMedia label="Hero graph comparison" width={720} height={540}/><p>A visible history of how your application evolves.</p></div>
    </section>
    <nav className="drift-jumps" aria-label="On this page"><div className="drift-shell">{[["changes", "What changed"], ["investigate", "Investigate"], ["how-it-works", "How it works"], ["scope", "Current scope"], ["faq", "FAQ"]].map(([id, label]) => <a href={`#${id}`} key={id}>{label}<span>↗</span></a>)}</div></nav>
    <section id="changes" className="drift-section drift-shell"><div className="drift-heading" data-aos="fade-up"><p className="drift-kicker">01 / Understand the difference</p><h2>Same application.<br />A different story.</h2><p>Each demonstration can produce a graph version. Compare two versions to see what changed, without manually piecing together workflows.</p></div><DriftComparison /></section>
    <section id="investigate" className="drift-section drift-surface"><div className="drift-shell"><div className="drift-split"><div data-aos="fade-up"><p className="drift-kicker">02 / Follow the change</p><h2>Sometimes what disappeared matters more.</h2><p>An inventory check appeared before. Now it is absent. That is a finding to investigate — it may have been skipped, or the path may no longer be reachable.</p><p>Compare the evidence before drawing a conclusion.</p></div><DriftMedia label="Removed-state detail" width={560} height={520}/></div>
      <div className="drift-details"><details><summary>Track coverage over time <span>+</span></summary><p>See whether repeated demonstrations exercise more or less of the application. A move from 68% to 72.2% is +4.2 percentage points of demonstrated coverage, not a quality score.</p><DriftMedia label="Coverage history" width={1100} height={520}/></details><details><summary>Keep declared intent in view <span>+</span></summary><p>See which intended paths now have evidence, and which remain unobserved as your application evolves.</p><Link href="/product/reconciliation">Explore Reconciliation →</Link><DriftMedia label="Declared intent vs. observed behavior" width={1100} height={670} master="1400 × 850"/></details><details><summary>Inspect the evidence and report <span>+</span></summary><p>Review both versions’ evidence basis, added and removed elements, changed transition frequencies, and coverage delta.</p><DriftMedia label="Version evidence panel" width={1000} height={620} master="1400 × 870"/><DriftMedia label="Graph Drift report" width={1100} height={720} master="1600 × 1050"/></details></div>
    </div></section>
    <section id="how-it-works" className="drift-section drift-shell"><div className="drift-heading" data-aos="fade-up"><p className="drift-kicker">03 / Build a behavioral history</p><h2>Demonstrate again.<br />See the difference.</h2></div><ol className="drift-steps">{[["Demonstrate", "Walk through a workflow in your application."], ["Create a version", "Tellann models the behavior it observed."], ["Demonstrate again", "Exercise the application after a change."], ["Compare", "Review changes and decide what to investigate."]].map(([name, copy], i) => <li key={name} data-aos="fade-up" data-aos-delay={i * 60}><span>0{i + 1}</span><h3>{name}</h3><p>{copy}</p></li>)}</ol><DriftRoles /><details className="drift-video"><summary>Graph Drift in 60 seconds <span>Video preview placeholder +</span></summary><DriftMedia label="Graph Drift demo video" width={960} height={540} master="1920 × 1080"/></details></section>
    <section id="scope" className="drift-section drift-surface"><div className="drift-shell"><div className="drift-heading" data-aos="fade-up"><p className="drift-kicker">04 / Know the evidence boundary</p><h2>Demonstrations today.<br />Continuous change ahead.</h2></div><div className="drift-phases">{[["PHASE 1 / CURRENT SCOPE", "Demonstration drift", "Version comparisons, coverage history, and drift against declared intent."], ["PHASE 2 / PLANNED", "Production baselines", "Understand drift against real production behavior."], ["PHASE 3 / PLANNED", "Anomaly intelligence", "Identify unexpected behavioral patterns over time."]].map(([phase, name, copy]) => <article key={phase}><p className="drift-kicker">{phase}</p><h3>{name}</h3><p>{copy}</p></article>)}</div><p className="drift-note">Roadmap phase does not determine plan entitlement. <Link href="/pricing">Explore plans →</Link></p></div></section>
    <section id="faq" className="drift-section drift-shell"><div className="drift-heading"><p className="drift-kicker">A few useful answers</p><h2>Before you compare.</h2></div><div className="drift-details">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div className="drift-related">{[["Behavior Graphs", "/product/behavior-graphs", "What does your application do?"], ["Reconciliation", "/product/reconciliation", "Does it match your intent?"], ["Coverage", "/product/coverage", "What have you exercised?"]].map(([name, href, copy]) => <Link href={href} key={href}><span>{name} ↗</span><small>{copy}</small></Link>)}</div></section>
    <section className="drift-final drift-shell" data-aos="fade-up"><p className="drift-kicker">Change is inevitable. Visibility is a choice.</p><h2>Your application will change.<br /><em>Keep its behavior visible.</em></h2><div className="drift-actions"><a className="drift-primary" href={appUrl}>Start a free trial ↗</a><Link href="/product/behavior-graphs">Explore Behavior Graphs →</Link></div></section>
  </main>;
}
