import { DashboardOverviewResponse } from "./types";

export const MOCK_MATURE_DASHBOARD_DATA: DashboardOverviewResponse = {
  lifecycle: "ACTIVE",
  maturity: "ESTABLISHED",
  application: {
    id: "app-snippets-123",
    name: "Snippets Application",
    environment: "development",
    plan: "solo",
  },
  onboarding: {
    applicationCreated: true,
    frontendConnected: true,
    backendConnected: true,
    telemetryVerified: true,
    firstDemonstrationCompleted: true,
    firstAnalysisReviewed: true,
  },
  telemetry: {
    frontendStatus: "ACTIVE",
    backendStatus: "ACTIVE",
    lastEventAt: "2026-08-12T07:45:12Z",
    eventCount: 4280,
  },
  analysis: {
    status: "COMPLETED",
    analysisCount: 14,
    latestAnalysisId: "analysis-9942",
    lastAnalysisAt: "2026-08-12T07:30:00Z",
  },
  summary: {
    workflowsDiscovered: { status: "MEASURED", value: 12, delta: 2 },
    statesObserved: { status: "MEASURED", value: 48, delta: 3 },
    transitionsObserved: { status: "MEASURED", value: 73, delta: 7 },
    sessionCount: { status: "MEASURED", value: 26, delta: 5 },
    findingsCount: {
      status: "MEASURED",
      value: { total: 12, critical: 1, high: 3, medium: 5, low: 3 },
    },
  },
  coverage: {
    workflowCoverage: { status: "MEASURED", value: 76.2, delta: 4.7 },
    stateCoverage: { status: "MEASURED", value: 81.0, delta: 2.1 },
    transitionCoverage: { status: "MEASURED", value: 69.4, delta: 5.8 },
    endpointCoverage: { status: "MEASURED", value: 72.0, delta: 1.2 },
    errorCoverage: { status: "MEASURED", value: 44.5, delta: 0 },
  },
  workflows: [
    {
      id: "wf-reg",
      name: "Registration",
      coverage: 92,
      stateCount: 8,
      missingPathCount: 1,
      demonstrationCount: 9,
      severity: "LOW",
    },
    {
      id: "wf-login",
      name: "Login & Auth",
      coverage: 74,
      stateCount: 6,
      missingPathCount: 3,
      demonstrationCount: 19,
      severity: "HIGH",
    },
    {
      id: "wf-checkout",
      name: "Checkout & Payment",
      coverage: 61,
      stateCount: 12,
      missingPathCount: 5,
      demonstrationCount: 24,
      severity: "CRITICAL",
    },
    {
      id: "wf-search",
      name: "Search & Browse",
      coverage: 48,
      stateCount: 7,
      missingPathCount: 4,
      demonstrationCount: 17,
      severity: "MEDIUM",
    },
    {
      id: "wf-profile",
      name: "Profile Management",
      coverage: 100,
      stateCount: 5,
      missingPathCount: 0,
      demonstrationCount: 4,
      severity: "INFO",
    },
  ],
  missingStates: [
    {
      id: "ms-1",
      stateName: "PAYMENT_FAILURE",
      workflowName: "Checkout & Payment",
      category: "ERROR",
      severity: "HIGH",
      evidence: "Not observed in 6 checkout demonstrations.",
    },
    {
      id: "ms-2",
      stateName: "EMPTY_CART",
      workflowName: "Cart & Checkout",
      category: "EMPTY",
      severity: "MEDIUM",
      evidence: "Empty state transitions have not been demonstrated.",
    },
    {
      id: "ms-3",
      stateName: "NO_SEARCH_RESULTS",
      workflowName: "Search & Browse",
      category: "EMPTY",
      severity: "MEDIUM",
      evidence: "No-results state has not been demonstrated.",
    },
    {
      id: "ms-4",
      stateName: "CHECKOUT_LOADING",
      workflowName: "Checkout & Payment",
      category: "LOADING",
      severity: "LOW",
      evidence: "Async payment processing spinner state unobserved.",
    },
  ],
  missingFlows: [
    {
      id: "mf-1",
      flowName: "Payment Failure Path",
      workflowName: "Checkout & Payment",
      path: ["CHECKOUT", "SUBMIT_PAYMENT", "PAYMENT_FAILED", "RETRY_FORM"],
      category: "FAILURE",
      severity: "HIGH",
      evidence: "Payment provider error code path not demonstrated.",
    },
    {
      id: "mf-2",
      flowName: "Authentication Failure",
      workflowName: "Login & Auth",
      path: ["LOGIN", "SUBMIT_CREDENTIALS", "AUTH_ERROR", "RESET_LINK"],
      category: "FAILURE",
      severity: "HIGH",
      evidence: "Invalid password recovery path unobserved.",
    },
    {
      id: "mf-3",
      flowName: "Retry Payment Recovery",
      workflowName: "Checkout & Payment",
      path: ["PAYMENT_FAILED", "UPDATE_CARD", "RESUBMIT_PAYMENT", "SUCCESS"],
      category: "RECOVERY",
      severity: "MEDIUM",
      evidence: "Card update recovery flow not demonstrated.",
    },
  ],
  opportunities: [
    {
      id: "opp-1",
      workflowId: "wf-checkout",
      workflowName: "Checkout & Payment",
      title: "Demonstrate Payment Failure in Checkout",
      description: "Checkout currently has 5 unobserved paths including payment declination and retry handling.",
      unobservedPathsCount: 5,
      suggestedSteps: [
        "Navigate to Checkout with active items",
        "Enter test card number triggering payment declination",
        "Observe error banner and click Retry Payment",
      ],
    },
    {
      id: "opp-2",
      workflowId: "wf-search",
      workflowName: "Search & Browse",
      title: "Demonstrate No Search Results Flow",
      description: "Search workflow missing zero-results empty state and filter reset path.",
      unobservedPathsCount: 4,
      suggestedSteps: [
        "Enter an unmatchable query in main search",
        "Verify empty results state",
        "Clear filters to recover product grid",
      ],
    },
  ],
  graph: {
    nodeCount: 48,
    edgeCount: 73,
    workflowCount: 12,
    entryPointCount: 5,
    exitPointCount: 9,
    nodes: [
      { id: "1", label: "ANONYMOUS", type: "entry", visitCount: 26 },
      { id: "2", label: "REGISTERED", type: "state", visitCount: 14 },
      { id: "3", label: "AUTHENTICATED", type: "state", visitCount: 22 },
      { id: "4", label: "SEARCH", type: "state", visitCount: 18 },
      { id: "5", label: "PRODUCT_VIEW", type: "state", visitCount: 24 },
      { id: "6", label: "CART", type: "state", visitCount: 19 },
      { id: "7", label: "CHECKOUT", type: "exit", visitCount: 12 },
    ],
    edges: [
      { id: "e1-2", source: "1", target: "2", label: "register" },
      { id: "e2-3", source: "2", target: "3", label: "verify_email" },
      { id: "e3-4", source: "3", target: "4", label: "search_products" },
      { id: "e4-5", source: "4", target: "5", label: "select_product" },
      { id: "e5-6", source: "5", target: "6", label: "add_to_cart" },
      { id: "e6-7", source: "6", target: "7", label: "proceed_checkout" },
    ],
  },
  sessions: [
    {
      id: "SES-2048",
      type: "Guided",
      durationSeconds: 840,
      eventCount: 682,
      workflowCount: 5,
      findingsCount: 7,
      timestamp: "12 mins ago",
      completenessPercentage: 99,
    },
    {
      id: "SES-2047",
      type: "Exploratory",
      durationSeconds: 480,
      eventCount: 327,
      workflowCount: 3,
      findingsCount: 2,
      timestamp: "Yesterday",
      completenessPercentage: 100,
    },
    {
      id: "SES-2046",
      type: "Validation",
      durationSeconds: 660,
      eventCount: 491,
      workflowCount: 4,
      findingsCount: 3,
      timestamp: "Aug 10",
      completenessPercentage: 97,
    },
  ],
  endpoints: {
    observedCount: { status: "MEASURED", value: 38 },
    averageLatencyMs: { status: "MEASURED", value: 241 },
    slowEndpoints: [
      {
        id: "ep-1",
        method: "GET",
        path: "/api/search",
        averageLatencyMs: 842,
        callCount: 1420,
      },
      {
        id: "ep-2",
        method: "GET",
        path: "/api/products",
        averageLatencyMs: 623,
        callCount: 2100,
      },
      {
        id: "ep-3",
        method: "POST",
        path: "/api/checkout",
        averageLatencyMs: 481,
        callCount: 340,
      },
    ],
    errorProneEndpoints: [
      {
        id: "ep-4",
        method: "POST",
        path: "/api/payment",
        errorRatePercentage: 4.8,
        errorCount: 16,
      },
      {
        id: "ep-5",
        method: "POST",
        path: "/api/auth/login",
        errorRatePercentage: 2.3,
        errorCount: 8,
      },
    ],
  },
  reports: [
    {
      id: "rep-1",
      title: "Executive Quality Report",
      type: "Executive",
      generatedAt: "14 mins ago",
    },
    {
      id: "rep-2",
      title: "Flow Coverage Report",
      type: "Coverage",
      generatedAt: "14 mins ago",
    },
    {
      id: "rep-3",
      title: "Missing State Report",
      type: "Gaps",
      generatedAt: "14 mins ago",
    },
    {
      id: "rep-4",
      title: "Endpoint Intelligence Report",
      type: "Endpoints",
      generatedAt: "14 mins ago",
    },
  ],
  coverageHistory: [
    {
      analysisId: "a1",
      label: "Analysis #1",
      timestamp: "Jul 15",
      workflow: 52.0,
      state: 61.0,
      transition: 48.0,
    },
    {
      analysisId: "a2",
      label: "Analysis #2",
      timestamp: "Jul 22",
      workflow: 61.5,
      state: 70.0,
      transition: 56.0,
    },
    {
      analysisId: "a3",
      label: "Analysis #3",
      timestamp: "Aug 01",
      workflow: 71.5,
      state: 78.9,
      transition: 63.6,
    },
    {
      analysisId: "a4",
      label: "Analysis #4",
      timestamp: "Aug 12",
      workflow: 76.2,
      state: 81.0,
      transition: 69.4,
    },
  ],
  privacy: {
    active: true,
    sensitiveFieldsBlockedCount: 14,
    replayMaskingEnabled: true,
    customRulesCount: 3,
  },
  usage: {
    planName: "Solo Plan",
    applicationsUsed: 1,
    applicationsLimit: 3,
    storageUsedMb: 820,
    storageLimitMb: 2048,
    retentionDays: 30,
  },
  liveDemonstration: null,
  healthIssues: [],
};
