import {
  AUTOMATION_STOP_REASON_KIND,
  AutomatedCodeEvidenceSchema,
  AutomationLimitsSchema,
  AutomationStopReasonSchema,
  ContractSummarySchema,
} from '@tellann/desktop-contracts';
import type { AutomatedCodeEvidence, AutomatedRetainedTrace, AutomatedRunSection, RenderTimingSample, AutomatedUnreachedState, StateRunRecord } from '@tellann/desktop-contracts';

/**
 * The Automated Run section of a QA report.
 *
 * Counterpart to `qa-frontend-report.ts` / `qa-backend-report.ts`: same discipline. It is
 * re-derived from the `QA_AUTOMATION_*` evidence events the run persisted, never from the desktop's
 * live state, so a report is reproducible from what was actually stored — and it is entirely
 * deterministic. No part of it is generated by a language model (QRS-RUN-008).
 *
 * It reports *what happened*, state by state, and how the run ended. It does not conclude that a
 * Flow step is "missing": an execution that fell short is evidence for reconciliation to weigh, and
 * it says so by keeping "the application prevented this" apart from "the run never got there"
 * (QRS-RUN-007).
 */

export type AutomationEvidenceEvent = {
  eventType: string;
  occurredAt: Date | string;
  localSequence?: number;
  scope?: string | null;
  normalizedRoute?: string | null;
  metadata: unknown;
};

export type AutomationRunInput = {
  mode: string;
  automation: unknown;
  initialStateKey?: string | null;
};

const normalizeKey = (value: unknown): string =>
  String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

const record = (value: unknown): Record<string, unknown> =>
  value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const text = (value: unknown): string | null => (typeof value === 'string' && value.length > 0 ? value : null);
const count = (value: unknown): number | null => (typeof value === 'number' && Number.isFinite(value) && value >= 0 ? Math.trunc(value) : null);
const iso = (value: Date | string): string => new Date(value).toISOString();

const RUNTIME_ERROR_TYPES = new Set(['QA_RUNTIME_ERROR', 'QA_PAGE_CRASH']);
/** A run that fails everywhere should not turn its report into a wall of diagnostics. */
const MAX_DIAGNOSTICS = 20;

export function summarizeAutomationEvidence(
  run: AutomationRunInput,
  events: AutomationEvidenceEvent[],
  declaredStateKeys: string[],
  reconciliationReports: Array<{ trueGaps?: unknown; trueGapTransitionsList?: unknown }> = [],
): AutomatedRunSection | null {
  if (run.mode !== 'AUTOMATED') return null;

  const automation = record(run.automation);
  const ordered = [...events].sort((a, b) =>
    new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime() || (a.localSequence ?? 0) - (b.localSequence ?? 0));

  const states: StateRunRecord[] = [];
  const blockedActions: AutomatedRunSection['blockedActions'] = [];
  const codeEvidence: AutomatedCodeEvidence[] = [];
  const retainedTraces: AutomatedRetainedTrace[] = [];
  const renderTiming = new Map<string, RenderTimingSample>();
  /** Declared state -> why an attempt to reach it failed, from the application's side. */
  const blockedTargets = new Map<string, string | null>();
  let current: StateRunRecord | null = null;
  let stopped: { stopReason: unknown; detail: string | null; steps: number | null; replans: number | null } | null = null;

  const close = (at: string) => {
    if (!current) return;
    current.exitedAt = at;
    current.durationMs = Math.max(0, new Date(at).getTime() - new Date(current.enteredAt).getTime());
    current = null;
  };

  for (const event of ordered) {
    const meta = record(event.metadata);
    const at = iso(event.occurredAt);
    switch (event.eventType) {
      case 'QA_AUTOMATION_STATE_EVALUATED': {
        const key = text(meta.recognizedStateKey);
        if (!key) break; // an unrecognised page is not a state visit.
        const stateKey = normalizeKey(key);
        // A re-evaluation of the same state with nothing done in it is the same visit.
        if (current && (current as StateRunRecord).stateKey === stateKey && !(current as StateRunRecord).action) break;
        close(at);
        const confidence = text(meta.confidence);
        current = {
          sequence: states.length,
          stateKey,
          confidence: confidence === 'HIGH' || confidence === 'MEDIUM' || confidence === 'LOW' ? confidence : null,
          scope: event.scope === 'IN_FLOW' ? 'IN_FLOW' : 'PRE_BOUNDARY',
          route: text(meta.path) ?? event.normalizedRoute ?? null,
          enteredAt: at,
          exitedAt: null,
          durationMs: null,
          action: null,
          errorCount: 0,
        };
        states.push(current);
        break;
      }
      case 'QA_AUTOMATION_ACTION_SELECTED': {
        if (!current) break;
        (current as StateRunRecord).action = {
          transitionId: text(meta.transitionId) ?? 'unknown',
          label: text(meta.action),
          actionClass: text(meta.actionClass),
          method: text(meta.method),
          expectedState: text(meta.expectedState) ? normalizeKey(meta.expectedState) : null,
          observedState: null,
          verified: null,
          error: null,
        };
        break;
      }
      case 'QA_AUTOMATION_ACTION_EXECUTED': {
        const action = (current as StateRunRecord | null)?.action;
        if (action && meta.ok === false) action.error = text(meta.error) ?? 'The action failed.';
        break;
      }
      case 'QA_AUTOMATION_ACTION_VERIFIED': {
        const action = (current as StateRunRecord | null)?.action;
        if (action) {
          action.verified = meta.ok === true;
          action.observedState = text(meta.observedState) ? normalizeKey(meta.observedState) : null;
        }
        if (meta.ok === false && text(meta.expectedState)) {
          blockedTargets.set(normalizeKey(meta.expectedState), 'The action was performed but the expected state did not follow.');
        }
        break;
      }
      case 'QA_AUTOMATION_ACTION_BLOCKED': {
        blockedActions.push({ reason: text(meta.reason) ?? 'UNKNOWN', transitionId: text(meta.transitionId), detail: text(meta.detail), at });
        // A policy block is the run's own safety rule talking, not the application preventing anything.
        const reason = text(meta.reason);
        if (text(meta.expectedState) && reason && !['ACTION_CLASS_BLOCKED', 'PRODUCTION_BLOCKED', 'EXTERNAL_ORIGIN_BLOCKED'].includes(reason)) {
          blockedTargets.set(normalizeKey(meta.expectedState), text(meta.detail));
        }
        break;
      }
      case 'QA_AUTOMATION_CODE_EVIDENCE': {
        // Re-validated on the way in: this is the platform reading what a desktop wrote, and a
        // malformed record must cost the report one entry, not the whole section.
        const parsed = AutomatedCodeEvidenceSchema.safeParse({ ...meta, at });
        if (parsed.success && codeEvidence.length < MAX_DIAGNOSTICS) codeEvidence.push(parsed.data);
        break;
      }
      case 'QA_AUTOMATION_RENDER_TIMING': {
        // Aggregated per component: a reading is taken as each state visit closes, but what a
        // component cost is a fact about the component, not about when it was read.
        for (const raw of Array.isArray(meta.samples) ? meta.samples : []) {
          const sample = record(raw);
          const component = text(sample.component);
          if (!component || (!renderTiming.has(component) && renderTiming.size >= MAX_DIAGNOSTICS)) continue;
          const total = renderTiming.get(component) ?? { component, states: [], mounts: 0, updates: 0, totalMs: 0, maxMs: 0 };
          total.mounts += count(sample.mounts) ?? 0;
          total.updates += count(sample.updates) ?? 0;
          const totalMs = Number(sample.totalMs);
          const maxMs = Number(sample.maxMs);
          if (Number.isFinite(totalMs) && totalMs >= 0) total.totalMs = Math.round((total.totalMs + totalMs) * 10) / 10;
          if (Number.isFinite(maxMs) && maxMs > total.maxMs) total.maxMs = maxMs;
          for (const state of Array.isArray(sample.states) ? sample.states : []) {
            const key = text(state) ? normalizeKey(state) : null;
            if (key && !total.states.includes(key)) total.states.push(key);
          }
          renderTiming.set(component, total);
        }
        break;
      }
      case 'QA_AUTOMATION_TRACE_RETAINED': {
        if (retainedTraces.length < MAX_DIAGNOSTICS) {
          retainedTraces.push({
            stateKey: text(meta.stateKey) ? normalizeKey(meta.stateKey) : null,
            reasons: Array.isArray(meta.reasons) ? meta.reasons.filter((reason): reason is string => typeof reason === 'string') : [],
            at,
          });
        }
        break;
      }
      case 'QA_AUTOMATION_STOPPED': {
        stopped = { stopReason: meta.stopReason, detail: text(meta.detail), steps: count(meta.steps), replans: count(meta.replans) };
        close(at);
        break;
      }
      default:
        if (RUNTIME_ERROR_TYPES.has(event.eventType) && current) (current as StateRunRecord).errorCount += 1;
    }
  }

  const parsedStop = AutomationStopReasonSchema.safeParse(stopped?.stopReason ?? automation.stopReason);
  const stopReason = parsedStop.success ? parsedStop.data : null;
  const kind = stopReason ? AUTOMATION_STOP_REASON_KIND[stopReason] : null;
  const reachedTarget = stopReason === 'TERMINAL_STATE_REACHED';
  const target = text(automation.targetTerminalStateKey);

  const reached = new Set(states.map((state) => state.stateKey));
  const unreachedStates: AutomatedUnreachedState[] = [];
  if (!reachedTarget) {
    for (const key of [...new Set(declaredStateKeys.map(normalizeKey))]) {
      if (reached.has(key)) continue;
      if (blockedTargets.has(key)) {
        unreachedStates.push({ stateKey: key, status: 'BLOCKED_BY_APPLICATION', detail: blockedTargets.get(key) ?? null });
      } else if (kind === 'APPLICATION' && stopReason !== 'UNSAFE_ACTION_BLOCKED' && target && normalizeKey(target) === key) {
        // UNSAFE_ACTION_BLOCKED is the run's own policy refusing, not the application preventing anything.
        unreachedStates.push({ stateKey: key, status: 'BLOCKED_BY_APPLICATION', detail: stopped?.detail ?? null });
      } else {
        unreachedStates.push({ stateKey: key, status: 'NOT_ATTEMPTED', detail: null });
      }
    }
  }

  const limits = AutomationLimitsSchema.safeParse(automation.limits);
  const contract = ContractSummarySchema.safeParse(automation.contract);
  return {
    pinned: {
      flowVersionId: text(automation.flowVersionId),
      initialStateKey: text(automation.initialStateKey) ?? run.initialStateKey ?? null,
      targetTerminalStateKey: target,
      executionProfileId: text(automation.executionProfileId),
      testPersonaId: text(automation.testPersonaId),
      runDataSetId: text(automation.runDataSetId),
      codeSnapshotId: text(automation.codeSnapshotId),
      instrumentationManifestVersion: text(automation.instrumentationManifestVersion),
      limits: limits.success ? limits.data : null,
      contract: contract.success ? contract.data : null,
    },
    outcome: {
      stopReason,
      kind,
      reachedTarget,
      detail: stopped?.detail ?? null,
      steps: stopped?.steps ?? null,
      replans: stopped?.replans ?? null,
    },
    states,
    preBoundaryStateCount: states.filter((state) => state.scope === 'PRE_BOUNDARY').length,
    inFlowStateCount: states.filter((state) => state.scope === 'IN_FLOW').length,
    unreachedStates,
    blockedActions,
    reconciliation: countAutomatedClassifications(reconciliationReports),
    codeEvidence,
    retainedTraces,
    renderTiming: [...renderTiming.values()],
  };
}

/** How many gaps the reconciliation engine attributed to each reason, across a run's reports. */
export function countAutomatedClassifications(
  reports: Array<{ trueGaps?: unknown; trueGapTransitionsList?: unknown }>,
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const report of reports) {
    for (const list of [report.trueGaps, report.trueGapTransitionsList]) {
      if (!Array.isArray(list)) continue;
      for (const entry of list) {
        const classification = text(record(entry).automatedClassification);
        if (classification) counts[classification] = (counts[classification] ?? 0) + 1;
      }
    }
  }
  return counts;
}
